CREATE table MOVIE (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
logo VARCHAR(255),
movieYear INT,
BIGINT movieRanking,
);

CREATE table RANKING(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
rankingCategory VARCHAR(255) NOT NULL,
rankingCreator BIGINT,
);

CREATE table USER(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,

;

CREATE table MOVIE_RANKING (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
BIGINT movie,
BIGINT ranking,
);

ALTER TABLE RANKING
ADD CONSTRAINT ranking_user_id
FOREIGN KEY (rankingCreator) REFERENCES User (id)